# .pre-commit-config.yaml
# This file configures the pre-commit hooks that will run automatically
# before each commit to ensure code quality and consistency.

repos:
# General and essential hooks for maintaining file health.
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml      # Checks YAML files for syntax errors.
    -   id: end-of-file-fixer # Ensures that files end with a newline.
    -   id: trailing-whitespace # Trims trailing whitespace from lines.

# Ruff: An extremely fast Python linter and code formatter.
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff
        args: [--fix] # The --fix argument tells Ruff to automatically fix any fixable errors.
    -   id: ruff-format
# Pylint: For deeper, more thorough static code analysis.
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - "--rcfile=.pylintrc"
# Pytest: For running tests to ensure code correctness.
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        stages: [pre-commit]
