services:
  training:
    build: .
    depends_on:
      db:
        condition: service_healthy
      mlflow:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: python src/synaptic_ids/training/run_training.py
    volumes:
      - ~/.kaggle:/root/.kaggle
