apiVersion: apps/v1
kind: Deployment
metadata:
  name: synaptic-ids-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: synaptic-ids
  template:
    metadata:
      labels:
        app: synaptic-ids
    spec:
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
        command: [ "/bin/sh", "-c" ]
        args:
            - |
              /cloud_sql_proxy -instances=synapticids:southamerica-east1:synapticids-db-instance=tcp:5432
        securityContext:
          runAsUser: 65532
          runAsNonRoot: true
      - name: synaptic-ids-api
        image: southamerica-east1-docker.pkg.dev/synapticids/synapticids-repo/synaptic-ids:latest
        command: [ "/bin/sh", "-c" ]
        args:
          - |
              while ! nc -z 127.0.0.1 5432; do
                echo "Waiting for the Cloud SQL proxy to be ready..."
                sleep 1
              done
              echo "Cloud SQL proxy is ready. Starting the application."
              uvicorn src.synaptic_ids.api.main:app --host 0.0.0.0 --port 8000
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@127.0.0.1:5432/synapticids_db"
        - name: REDIS_URL
          value: "redis://10.44.95.43:6379"
